import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import postgres, { type Sql } from 'postgres';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { createApp } from '../app.js';
import { createPostgresDatabase, type PostgresDatabase } from './client.js';

const testUrl = process.env.POSTGRES_TEST_URL;
const schema = `qa_transfers_${randomUUID().replaceAll('-', '')}`;
let admin: Sql;
let db: PostgresDatabase;

const lineup = {
  tournamentId: 'qa-tournament', gameweekId: 'qa-gw-1', formation: '4-3-3',
  starters: ['gk-1', 'def-1', 'def-2', 'def-3', 'def-4', 'mid-1', 'mid-2', 'mid-3', 'fwd-1', 'fwd-2', 'fwd-3'],
  bench: ['gk-2', 'def-5', 'mid-4', 'mid-5'],
  captainId: 'fwd-1', viceCaptainId: 'mid-1',
};

async function seed() {
  const now = new Date().toISOString();
  await db.execute("insert into tournaments(id,name,status,budget_cents,created_at) values('qa-tournament','QA','ACTIVE',10000000000,$1)", [now]);
  await db.execute("insert into gameweeks(id,tournament_id,week_number,name,deadline_at,status) values('qa-gw-1','qa-tournament',1,'QA GW', '2099-01-01T00:00:00.000Z','OPEN')");
  for (let i = 1; i <= 12; i += 1) await db.execute('insert into clubs(id,name,code,active) values($1,$2,$3,true)', [`club-${i}`, `Club ${i}`, `C${i}`]);
  let club = 1;
  for (const [position, count] of [['GK', 3], ['DEF', 7], ['MID', 7], ['FWD', 5]] as const) {
    for (let i = 1; i <= count; i += 1) {
      const id = `${position.toLowerCase()}-${i}`;
      await db.execute("insert into players(id,club_id,name,position,price_cents,status,active,updated_at) values($1,$2,$3,$4,500000000,'ACTIVE',true,$5)",
        [id, `club-${club}`, id, position, now]);
      await db.execute("insert into tournament_players(tournament_id,player_id,price_cents,active) values('qa-tournament',$1,500000000,true)", [id]);
      club = club === 12 ? 1 : club + 1;
    }
  }
}

async function createManager(name: string) {
  const agent = request.agent(createApp({ postgresDb: db, secureCookies: false }));
  await agent.post('/api/auth/register').send({
    email: `${name}@example.test`, username: name, password: 'correct horse battery staple', managerName: name,
  }).expect(201);
  const response = await agent.post('/api/onboarding').send({ ...lineup, teamName: `QA ${name}` }).expect(201);
  return { agent, teamId: response.body.team.id as string };
}

async function teamMoney(teamId: string) {
  return await db.one<{ bank_cents: string | number; free_transfers: number }>(
    'select bank_cents,free_transfers from fantasy_teams where id=$1', [teamId]);
}

describe.skipIf(!testUrl)('transferencias contra PostgreSQL real en esquema aislado', () => {
  beforeAll(async () => {
    const url = new URL(testUrl!);
    admin = postgres(url.toString(), { max: 1, prepare: false });
    await admin.unsafe(`create schema "${schema}"`);
    db = createPostgresDatabase({ url: url.toString(), maxConnections: 1 });
    // Supabase's pooler ignores startup search_path options. Keep a single
    // session and verify an explicit SET before any migration or fixture write.
    await db.execute(`set search_path to "${schema}", public`);
    const current = await db.one<{ name: string }>('select current_schema() as name');
    if (current.name !== schema) throw new Error(`El esquema de prueba no está aislado: ${current.name}.`);
    const migration = await readFile('supabase/migrations/202609150001_initial_schema.sql', 'utf8');
    await db.execute(migration);
    await db.execute('create table app_schema_migrations(version text primary key, checksum text not null, applied_at timestamptz not null default now())');
    const rlsMigration = await readFile('supabase/migrations/202609190001_rls_isolation.sql', 'utf8');
    // Preserve production while exercising the same policy definitions inside
    // this disposable QA schema. All explicit public table references are scoped.
    await db.execute(rlsMigration.replaceAll('public.', `"${schema}".`));
    await db.execute(`grant usage on schema "${schema}" to fantasy_lpf_app`);
  }, 120_000);

  beforeEach(async () => {
    const current = await db.one<{ name: string }>('select current_schema() as name');
    if (current.name !== schema) throw new Error(`Se perdió el esquema aislado: ${current.name}.`);
    await db.execute('truncate table users,tournaments,clubs cascade');
    await seed();
  }, 120_000);

  afterAll(async () => {
    await db?.close();
    if (admin) {
      // Only the schema generated by this test is removed; public production data is untouched.
      await admin.unsafe(`drop schema if exists "${schema}" cascade`);
      await admin.end({ timeout: 5 });
    }
  }, 30_000);

  it('cotiza ganancia y depreciación, rechaza precio obsoleto y confirma compra, banco, ownership e historial', async () => {
    const ana = await createManager('ana');
    const beto = await createManager('beto');
    await db.execute("update tournament_players set price_cents=580000000 where player_id in ('def-5','def-6')");

    const quote = await ana.agent.get('/api/team?tournamentId=qa-tournament&gameweekId=qa-gw-1').expect(200);
    expect(quote.body.team.squad.find((p: { id: string }) => p.id === 'def-5')).toMatchObject({
      purchasePriceCents: 500_000_000, currentPriceCents: 580_000_000,
      sellingPriceCents: 540_000_000, profitLossCents: 40_000_000,
    });
    const before = await teamMoney(ana.teamId);
    const stale = await ana.agent.post('/api/transfers').send({ tournamentId: lineup.tournamentId,
      gameweekId: lineup.gameweekId, items: [{
      playerOutId: 'def-5', playerInId: 'def-6', expectedBuyPriceCents: 1, expectedSellPriceCents: 1,
    }] }).expect(409);
    expect(stale.body.error.code).toBe('PRICE_CHANGED');
    expect((await teamMoney(ana.teamId)).bank_cents).toBe(before.bank_cents);
    expect((await db.one<{ count: number }>('select count(*)::int as count from transfers')).count).toBe(0);

    const valid = await ana.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId,
      items: [{ playerOutId: 'def-5', playerInId: 'def-6',
        expectedBuyPriceCents: 580_000_000, expectedSellPriceCents: 540_000_000 }],
    }).expect(201);
    expect(valid.body.transfer).toMatchObject({
      bankBeforeCents: 2_500_000_000, bankAfterCents: 2_460_000_000, pointsCost: 0,
    });
    expect(valid.body.team.freeTransfers).toBe(0);
    expect(valid.body.team.squad.find((p: { id: string }) => p.id === 'def-6')).toMatchObject({
      purchasePriceCents: 580_000_000, currentPriceCents: 580_000_000,
    });
    const item = await db.one<{ sell_price_cents: string; buy_price_cents: string; purchase_price_cents: string; profit_loss_cents: string }>(
      'select sell_price_cents,buy_price_cents,purchase_price_cents,profit_loss_cents from transfer_items where transfer_id=$1',
      [valid.body.transfer.id]);
    expect(item).toMatchObject({ sell_price_cents: '540000000', buy_price_cents: '580000000',
      purchase_price_cents: '500000000', profit_loss_cents: '40000000' });
    expect(valid.body.team.transferHistory[0]).toMatchObject({ sellingPrice: 5.4, purchasePrice: 5, profitLoss: 0.4 });

    await db.execute("update tournament_players set price_cents=420000000 where player_id='def-5'");
    const depreciated = await beto.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId,
      items: [{ playerOutId: 'def-5', playerInId: 'def-6',
        expectedBuyPriceCents: 580_000_000, expectedSellPriceCents: 420_000_000 }],
    }).expect(201);
    expect(depreciated.body.transfer.bankAfterCents).toBe(2_340_000_000);
    expect(depreciated.body.team.transferHistory[0]).toMatchObject({ sellingPrice: 4.2, profitLoss: -0.8 });

    const duplicate = await ana.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId,
      items: [{ playerOutId: 'def-5', playerInId: 'def-6' }],
    }).expect(422);
    expect(duplicate.body.error.code).toBe('TEAM_RULE_VIOLATION');
    expect((await db.one<{ count: number }>('select count(*)::int as count from transfers where fantasy_team_id=$1', [ana.teamId])).count).toBe(1);
  }, 120_000);

  it('mantiene ligas privadas y datos deportivos con el rol RLS restringido', async () => {
    const ana = await createManager('ana');
    const beto = await createManager('beto');
    const catalog = await ana.agent.get('/api/catalog?tournamentId=qa-tournament').expect(200);
    expect(catalog.body.players.length).toBeGreaterThan(15);
    const created = await ana.agent.post('/api/leagues').send({
      tournamentId: 'qa-tournament', name: 'Liga RLS QA',
    }).expect(201);
    const code = created.body.league.code as string;
    await beto.agent.post('/api/leagues/join').send({ code }).expect(201);
    const leagues = await beto.agent.get('/api/leagues?tournamentId=qa-tournament').expect(200);
    expect(leagues.body.leagues).toHaveLength(1);
    const leaderboard = await ana.agent.get(`/api/leagues/${created.body.league.id}/leaderboard`).expect(200);
    expect(leaderboard.body.leaderboard).toHaveLength(2);
    expect(leaderboard.body.leaderboard.some((entry: { fantasyTeamId: string }) => entry.fantasyTeamId === beto.teamId)).toBe(true);
    await beto.agent.delete(`/api/leagues/${created.body.league.id}/membership`).expect(204);
    const after = await ana.agent.get(`/api/leagues/${created.body.league.id}/leaderboard`).expect(200);
    expect(after.body.leaderboard).toHaveLength(1);
  }, 120_000);

  it('aplica -4 al batch adicional y el comodín conserva la transferencia gratuita', async () => {
    const regular = await createManager('regular');
    const wildcard = await createManager('wildcard');
    const items = [{ playerOutId: 'def-5', playerInId: 'def-6' },
      { playerOutId: 'mid-4', playerInId: 'mid-6' }];
    const batch = await regular.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId, items,
    }).expect(201);
    expect(batch.body.transfer.pointsCost).toBe(4);
    expect(batch.body.team.freeTransfers).toBe(0);
    expect((await db.one<{ count: number }>('select count(*)::int as count from transfer_items where transfer_id=$1', [batch.body.transfer.id])).count).toBe(2);

    await wildcard.agent.post('/api/chips/activate').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId, chipId: 'wildcard',
    }).expect(200);
    const chipBatch = await wildcard.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId, items,
    }).expect(201);
    expect(chipBatch.body.transfer.pointsCost).toBe(0);
    expect(chipBatch.body.team.freeTransfers).toBe(1);
    expect((await db.one<{ wildcard_used: boolean }>('select wildcard_used from transfers where id=$1', [chipBatch.body.transfer.id])).wildcard_used).toBe(true);
  }, 120_000);

  it('revierte una falla después de insertar la transferencia y respeta el deadline', async () => {
    const manager = await createManager('rollback');
    await db.execute(`create function fail_qa_transfer_item() returns trigger language plpgsql as $$
      begin raise exception 'QA forced rollback'; end $$`);
    await db.execute('create trigger fail_qa_transfer_item before insert on transfer_items for each row execute function fail_qa_transfer_item()');
    const before = await teamMoney(manager.teamId);
    const failure = await manager.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId,
      items: [{ playerOutId: 'def-5', playerInId: 'def-6' }],
    }).expect(500);
    expect(failure.body.error.code).toBe('INTERNAL_ERROR');
    expect(await teamMoney(manager.teamId)).toEqual(before);
    expect((await db.one<{ count: number }>('select count(*)::int as count from transfers')).count).toBe(0);
    expect((await db.one<{ count: number }>("select count(*)::int as count from squad_players where fantasy_team_id=$1 and player_id='def-5'", [manager.teamId])).count).toBe(1);
    expect((await db.one<{ count: number }>("select count(*)::int as count from squad_players where fantasy_team_id=$1 and player_id='def-6'", [manager.teamId])).count).toBe(0);
    await db.execute('drop trigger fail_qa_transfer_item on transfer_items');
    await db.execute('drop function fail_qa_transfer_item()');

    await db.execute("update gameweeks set deadline_at='2000-01-01T00:00:00.000Z' where id='qa-gw-1'");
    const closed = await manager.agent.post('/api/transfers').send({
      tournamentId: lineup.tournamentId, gameweekId: lineup.gameweekId,
      items: [{ playerOutId: 'def-5', playerInId: 'def-6' }],
    }).expect(409);
    expect(closed.body.error.code).toBe('DEADLINE_PASSED');
    expect((await db.one<{ count: number }>('select count(*)::int as count from transfers')).count).toBe(0);
  }, 120_000);
});
